### PR TITLE
Add AJAX subscription endpoint

### PR DESCRIPTION
**Pull request by aatishnn**

### CODE REVIEW

**Comment by matthiask** [comment]
Thank you! 

Please add tests (currently we have 100% code coverage), and run your code through [flake8](https://flake8.readthedocs.io/). Also, messages should use i18n -- the default views also do this, e.g. https://github.com/matthiask/django-newsletter-subscription/blob/master/newsletter_subscription/views.py#L120

**Comment by aatishnn** [comment]
@matthiask Thank you. Will do. I am still learning.

**Comment by matthiask** [comment]
Just ask if you need help / additional pointers!

**Comment by aatishnn** [comment]
@matthiask is this ok now?

**Comment by matthiask** [comment]
Looks good, thanks! 

I have a suggestion though, maybe it would be useful to make it easier to differentiate between errors and successes, either by adding `success:True` or `success:False` to the JSON object, or by renaming the `message` key to `success` or `error`. What do you think?

**Comment by aatishnn** [comment]
I went with renaming the keys.

**Pull request merged**
